name: shell commands

on: [push] # can add more events inside brackets like pull

jobs:
    run-shell-command:
        runs-on: ubuntu-latest
        steps: # add array of objects
            - name: echo a string
              run: echo "Hello $USER"
            - name: multi line commands
              run: |
                node -v
                npm -v
                